- hosts: all
  vars:
    package: 
      - httpd
      - wget
      - tree
      - git
  tasks:
  - name: install packages
    yum:
      name: "{{ package }}" 
      
      state: latest
 

  - name: Start apache
    service:
      name: "{{ package }}"
      state: started
   